server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eshop
    username: postgres
    password: YourStrong@Passw0rd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: true
springdoc:
  api-docs:
    path: /docs/api
  swagger-ui:
    path: /docs/ui
management:
  endpoints:
    web:
      exposure:
        include: health,env,metrics
  endpoint:
    health:
      show-details: always
    env:
      show-values: always