CREATE TABLE IF NOT EXISTS product (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    genre VARCHAR(128) NOT NULL,
    unit_price NUMERIC(20,2),
    unit_in_stock INTEGER NOT NULL,
    release_date DATE,
    image_uri VARCHAR(200) NOT NULL,
    PRIMARY KEY (id)
);